name: Broadcast
version: 0.1
api: [1.0.0]
author: TylerGamesTV
main: Main\Main
commands:
  example:
    description: Broadcast A Message
    usage: "/example"
    permission: example.command
permissions:
  example.command:
    default: true
